# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global.parameters]
stack_name = "SES"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
resolve_s3 = true

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"




# DEV advanced account
[dev.deploy.parameters]
stack_name = 'CAST-SES'
s3_bucket = 'cost-reporting-vw'
region = 'eu-west-1'
capabilities = 'CAPABILITY_IAM'
tags=" GITC- GITC-Risk Class=\"3\" GITC- Data Classification=\"internal\" GITC- Data Classification=\"true\" GITC-ApplicationID=\"82299\" backup=\"true\" "
parameter_overrides=[
# INFRA VARIABLES
    'Env=dev',
    'CreateNewSecret=False',
    'GeneralName=CAST',
    'VPCId=vpc-0517670858bad1b7b',
    'Subnet1=subnet-0c0de0a7916e385ec',
    'Subnet2=subnet-092ee8f5c41040211',
    'BucketInputOverview=vw-lambda-reporting-manual-input',
    'BucketInput=vw-lambda-reporting-output']



# DEV advanced account
[prod.deploy.parameters]
stack_name = 'CAST-SES'
s3_bucket = 'cast-deployment'
region = 'eu-west-1'
capabilities = 'CAPABILITY_IAM'
tags=" GITC- GITC-Risk Class=\"3\" GITC- Data Classification=\"internal\" GITC- Data Classification=\"true\" GITC-ApplicationID=\"82299\" backup=\"true\" "
parameter_overrides=[
# INFRA VARIABLES
    'Env=prod',
    'CreateNewSecret=False',
    'GeneralName=CAST-SES',
    'BucketInputOverview=cast-input',
    'BucketInput=cast-output']