AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  SES
  Sample SAM Template for SES

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 120
    MemorySize: 128

Parameters:
  BucketInput:
    Type: String
    Description: input bucket for lambda
    NoEcho: true

  BucketInputOverview:
    Type: String
    Description: input bucket for overview file
    NoEcho: true

  VPCId:
    Type: String
    Description: Subnet id
    NoEcho: true

  Subnet1:
    Type: String
    Description: Subnet id
    NoEcho: true

  Subnet2:
    Type: String
    Description: Subnet id
    NoEcho: true

  Prefix:
    Description: project prefix
    Type: String
    Default: CAST-

  PrefixLowercase:
    Description: project prefix
    Type: String
    Default: cast-

Resources:
  TriggerFunction:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: Trigger
      Description: Triggers CAST-SES
      Role: !GetAtt InvokingRole.Arn
      CodeUri: trigger/
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      VpcConfig:
        SecurityGroupIds:
          - !GetAtt CASTLambdasSG.GroupId
        SubnetIds:
          - !Ref Subnet1
          - !Ref Subnet2

  SendingFunction:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: Sender
      Description:  CAST email sending Lmabda. Distributes Cost Reports according to Sending list from CRC
      Role: !GetAtt SESRole.Arn
      CodeUri: app/
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Environment:
        Variables:
          BUCKET_INPUT: !Ref BucketInput
          BUCKET_INPUT_OVERVIEW: !Ref BucketInputOverview

  CASTLambdasSG:
    Type: AWS::EC2::SecurityGroup
    DeletionPolicy: Delete
    Properties:
      VpcId: !Ref VPCId
      GroupDescription: DPP-CAST security group for Lambda actions
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
          Description: allows Lambda connections to other services

  InvokingRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"

  InvokingPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: CASTTriggerPolicy
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - lambda:invokeFunction
            Resource:
              - !GetAtt SendingFunction.Arn

          - Effect: Allow
            Action:
              - lambda:listFunctions
            Resource:
              - "*"
      Roles:
        - Ref: InvokingRole

  SESRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"

  SESPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: CASTSendPolicy
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - ses:SendEmail
              - ses:SendRawEmail
            Resource:
              - "*"
            Condition:
              ForAnyValue:StringEquals:
                ses:FromAddress:
                  [
                    "dpp.clearing.office.vwag.r.wob@volkswagen.de",
                    "cast.ses.2@efs.at",
                    "cast.ses.1@efs.at",
                    "extern.gregor.zopf@volkswagen.de"
                  ]
      Roles:
        - Ref: SESRole

  S3Policy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: SesS3
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - s3:ListBucket
              - s3:PutObject
              - s3:GetObject
              - s3:PutObjectTagging
              - s3:GetBucketLocation
            Resource:
              - !Sub arn:aws:s3:::${PrefixLowercase}*
              - !Sub arn:aws:s3:::${PrefixLowercase}*/*
              - !Sub arn:aws:s3:::${Prefix}*
              - !Sub arn:aws:s3:::${Prefix}*/*
              - !Sub arn:aws:s3:::vw-lambda-*
              - !Sub arn:aws:s3:::vw-lambda-*/*
      Roles:
        - Ref: SESRole
