AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Automatic Email-sending application

Globals:
  Function:
    Timeout: 120
    MemorySize: 128

Parameters:
  BucketInput:
    Type: String
    Description: input bucket for lambda
    NoEcho: true

  BucketInputOverview:
    Type: String
    Description: input bucket for overview file
    NoEcho: true

  VPCId:
    Type: String
    Description: Subnet id
    NoEcho: true

  Subnet1:
    Type: String
    Description: Subnet id
    NoEcho: true

  Subnet2:
    Type: String
    Description: Subnet id
    NoEcho: true

  Prefix:
    Description: project prefix
    Type: String
    Default: EMAIL-

  PrefixLowercase:
    Description: project prefix
    Type: String
    Default: email-

  Env:
    Description: stage
    Type: String


Conditions:
  ProdResources: !Equals [!Ref Env, prod]

Resources:
  SenderFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 240
      MemorySize: 400
      FunctionName: !Sub ${Prefix}Sender
      Description: Distributes emails according to received sending list 
      Role: !GetAtt SESRole.Arn
      CodeUri: SenderFunction/
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Layers:
        - !Ref SharedLayer
      Environment:
        Variables:
          BUCKET_INPUT: !Ref BucketInput
          BUCKET_INPUT_OVERVIEW: !Ref BucketInputOverview


  CASTLambdasSG:
    Type: AWS::EC2::SecurityGroup
    DeletionPolicy: Delete
    Properties:
      VpcId: !Ref VPCId
      GroupDescription: security group for Lambda actions
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
          Description: allows Lambda connections to other services

  InvokingRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"

  InvokingPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: TriggerPolicy
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - lambda:invokeFunction
            Resource:
              - !GetAtt Function.Arn

          - Effect: Allow
            Action:
              - lambda:listFunctions
            Resource:
              - "*"
      Roles:
        - Ref: InvokingRole

  SESRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"

  SESPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: CASTSendPolicy
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - ses:SendEmail
              - ses:SendRawEmail
            Resource:
              - "*"
            Condition:
              ForAnyValue:StringEquals:
                ses:FromAddress:
                  [
                  "test.ses.1@gmail.at"   
                  ]
      Roles:
        - Ref: SESRole

  S3Policy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: SesS3
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - s3:ListBucket
              - s3:PutObject
              - s3:GetObject
              - s3:PutObjectTagging
              - s3:GetBucketLocation
            Resource:
              - !Sub arn:aws:s3:::${PrefixLowercase}*
              - !Sub arn:aws:s3:::${PrefixLowercase}*/*

      Roles:
        - Ref: SESRole

  SharedLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: SharedLayer
      Description: Some code to share with the other lambda functions
      ContentUri: ./shared
      CompatibleRuntimes:
        - python3.11

      RetentionPolicy: Delete
