# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global.parameters]
stack_name = "SES"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
resolve_s3 = true

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"


# DEV advanced account
[dev.deploy.parameters]
stack_name = 'Mail'
s3_bucket = 'mail-artifacts
region = 'eu-west-1'
capabilities = 'CAPABILITY_IAM'
parameter_overrides = [
    # INFRA VARIABLES
    'Env=dev',
    'CreateNewSecret=False',
    'GeneralName=Mail',
]


# DEV advanced account
[prod.deploy.parameters]
stack_name = 'Mail'
s3_bucket = 'cast-deployment'
region = 'eu-west-1'
capabilities = 'CAPABILITY_IAM'
parameter_overrides = [
    # INFRA VARIABLES
    'Env=dev',
    'CreateNewSecret=False',
    'GeneralName=Mail',
]